<?php


namespace Tookan\DefaultValues;


class TookanCountries{
    public static $Values = [
        "KWT" => [
            "NAME" => "Kuwait",
            "TIMEZONE" => "-180",
            "TEAM_ID" => "1168385",
            "COUNTRY_CODE" => "+965",
            "ALPHA_CODE" => "KWT",
            "TIMEZONE_CODE" => "Asia/Kuwait",
            "WEEKEND" => "Friday",
            "START_HOUR_WORK" => 9,
            "END_HOUR_WORK" => 23,
            "NUMBER_OF_TASKS" => 30,
            "MESSAGE_BIRD_SURVEY" => "https://flows.messagebird.com/flows/ece06cb9-6031-4f40-82aa-4c1e906b70cc/invoke",
            "MESSAGE_BIRD_DONT_COVER" => "https://flows.messagebird.com/flows/2820f3b6-c7a4-452e-85ec-80874a79eba7/invoke",
        ],
        "KSA" => [
            "NAME" => "Saudi Arabia",
            "TIMEZONE" => "-180",
            "TEAM_ID" => "1234041",
            "COUNTRY_CODE" => "+966",
            "ALPHA_CODE" => "KSA",
            "TIMEZONE_CODE" => "Asia/Riyadh",
            "WEEKEND" => "",
            "START_HOUR_WORK" => 9,
            "END_HOUR_WORK" => 20,
            "NUMBER_OF_TASKS" => 30,
            "MESSAGE_BIRD_SURVEY" => "https://flows.messagebird.com/flows/16db3835-7c4c-4a0b-9d30-e5cb629d735d/invoke",
            "MESSAGE_BIRD_DONT_COVER" => "https://flows.messagebird.com/flows/3892c748-176d-459d-a2d8-220c4975fafe/invoke",
        ],
        "OMN" => [
            "NAME" => "Oman",
            "TIMEZONE" => "-240",
            "TEAM_ID" => "1228392",
            "COUNTRY_CODE" => "+968",
            "ALPHA_CODE" => "OMN",
            "TIMEZONE_CODE" => "Asia/Muscat",
            "WEEKEND" => "Friday",
            "START_HOUR_WORK" => 11,
            "END_HOUR_WORK" => 19,
            "NUMBER_OF_TASKS" => 20,
            "MESSAGE_BIRD_SURVEY" => "https://flows.messagebird.com/flows/f712c708-938f-4d2d-8705-7c77a6554ba3/invoke",
            "MESSAGE_BIRD_DONT_COVER" => "https://flows.messagebird.com/flows/6a25fb96-7cc6-42ed-9a78-16f57bcc3f5d/invoke",
        ],
        "UAE" => [
            "NAME" => "United Arab Emirates",
            "TIMEZONE" => "-240",
            "TEAM_ID" => "1105452",
            "COUNTRY_CODE" => "+971",
            "ALPHA_CODE" => "UAE",
            "TIMEZONE_CODE" => "Asia/Dubai",
            "WEEKEND" => "saturday",
            "START_HOUR_WORK" => 11,
            "END_HOUR_WORK" => 21,
            "NUMBER_OF_TASKS" => 30,
            "MESSAGE_BIRD_SURVEY" => "https://flows.messagebird.com/flows/28be5e32-b3ac-45be-a733-176a679b72ce/invoke",
            "MESSAGE_BIRD_DONT_COVER" => "https://flows.messagebird.com/flows/2ecfbfc5-99ef-4d0c-a45e-379107133455/invoke",
        ],
        "BHR" => [
            "NAME" => "Bahrain",
            "TIMEZONE" => "-180",
            "TEAM_ID" => "1274892",
            "COUNTRY_CODE" => "+973",
            "ALPHA_CODE" => "BHR",
            "TIMEZONE_CODE" => "Asia/Bahrain",
            "WEEKEND" => "Friday",
            "START_HOUR_WORK" => 9,
            "END_HOUR_WORK" => 23,
            "NUMBER_OF_TASKS" => 30,
            "MESSAGE_BIRD_SURVEY" => "https://flows.messagebird.com/flows/d6871f9b-5703-45cd-8aec-149d5fb3bbc4/invoke",
            "MESSAGE_BIRD_DONT_COVER" => "https://flows.messagebird.com/flows/b8902b58-b48a-47f3-833c-86d9844852aa/invoke",
        ],
        "QAT" => [
            "NAME" => "Qatar",
            "TIMEZONE" => "-180",
            "TEAM_ID" => "1492973",
            "COUNTRY_CODE" => "+974",
            "ALPHA_CODE" => "QAT",
            "TIMEZONE_CODE" => "Asia/Qatar",
            "WEEKEND" => "Friday",
            "START_HOUR_WORK" => 9,
            "END_HOUR_WORK" => 23,
            "NUMBER_OF_TASKS" => 30,
            "MESSAGE_BIRD_SURVEY" => "",
            "MESSAGE_BIRD_DONT_COVER" => "",
        ],
        "GREEN_CLOSET:KSA" => [
            "NAME" => "Saudi Arabia",
            "TIMEZONE" => "-180",
            "TEAM_ID" => "1507488",
            "COUNTRY_CODE" => "+966",
            "ALPHA_CODE" => "KSA",
            "TIMEZONE_CODE" => "Asia/Riyadh",
            "WEEKEND" => "",
            "START_HOUR_WORK" => 9,
            "END_HOUR_WORK" => 20,
            "NUMBER_OF_TASKS" => 30,
            "MESSAGE_BIRD_SURVEY" => "",
            "MESSAGE_BIRD_DONT_COVER" => "",
        ],
        "GREEN_CLOSET:UAE" => [
            "NAME" => "United Arab Emirates",
            "TIMEZONE" => "-240",
            "TEAM_ID" => "1517967",
            "COUNTRY_CODE" => "+971",
            "ALPHA_CODE" => "UAE",
            "TIMEZONE_CODE" => "Asia/Dubai",
            "WEEKEND" => "saturday",
            "START_HOUR_WORK" => 11,
            "END_HOUR_WORK" => 21,
            "NUMBER_OF_TASKS" => 30,
            "MESSAGE_BIRD_SURVEY" => "",
            "MESSAGE_BIRD_DONT_COVER" => "",
        ],
    ];
}